
# .sops.yaml
# Any file that contains secret on the name will be encrypted on on data/stringData
# when you run sops -e

creation_rules:
  - path_regex: .*secret.*\.ya?ml 
    encryted_regex: '^(data|stringData)$'
    age: age1ck6ak0u4tuxydx4dsw2lc9apae1k5qvcmzx59j0ktkavfhjkepa54se0fp15
