apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-agent
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: personal-agent
spec:
  project: default
  source:
    repoURL: https://github.com/josecarlosjr/app-cla.git
    targetRevision: main
    path: k8s/personal-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: personal-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
