apiVersion: ENC[AES256_GCM,data:pOU=,iv:z5ZRLLBN+5xX2TMkNmXcyJHeWYpKAh4ZyZoIXxCQxjo=,tag:EZHAbY1hMQPWFp54oKaxdw==,type:str]
kind: ENC[AES256_GCM,data:SsKMoqjv,iv:+10eqBrZR2mdLyngJjnbVyUW0aovd92Rjmz/n/uel08=,tag:UPk5c7IJJntvf96G4FlNHA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:US1si5DWgYJipGtHCg==,iv:KNPTYKXOvLDXhRhaN//xY36WDKBdajDGJV71UPn3aPA=,tag:g8vIQBmoOe5mzFeS/Z7KxQ==,type:str]
    namespace: ENC[AES256_GCM,data:t79Iowzkq7pnutkOGP0=,iv:uDL+oOpzVF2su4EwWO4aWyYgxVGUuWkCCt3SxNN1GNk=,tag:aJ8/N2guxLwht7lB8kRx0A==,type:str]
type: ENC[AES256_GCM,data:4rcX733U,iv:80dzOUMRm2peuVTl13o28G3WEd033vrGZG3ea7l+w1Q=,tag:OerSFuMNEqz4IOZgJsBGsw==,type:str]
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:AdQTcHwGMZJqoC/ikEBk4acqM0OEiiRQZC7n0B8yjSS5cTMWyCwt,iv:E2mZ7tDcv8VsYyp4PdhBJNr/kWxKGV91TqdCN4jHCWs=,tag:clLNLDAx/s1o53YIsx8xMA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:dZhZJSLSVpuC47WwOzj3Bun1L2NH7n/NRg4v3Z9/myW0VZ8okZbzYcfuiC7nEQ==,iv:vX2NjPpKHfIXMDFZf3TgD1UmOwGWrg6JA4xhYvjrY8A=,tag:jzMd6uU+iDnxkuMHRU/TWw==,type:str]
    TELEGRAM_ALLOWED_USER_ID: ENC[AES256_GCM,data:HSZ6kR8b0UYc,iv:RCLjHT7D7G78RFrws93rYsIl+q88GmOSFMKfaiGPApI=,tag:GeylkDOhRsC0KW6sQ2WWBA==,type:int]
sops:
    age:
        - recipient: age1x6ka0u4tudyx4dsw2lc9apaejk5qvcmzx59j0ktkavfhjkepa54se0fpl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQkl2MVI3MGJuVXpuL0dn
            V0JwL1h0QnlCb0k5dTBvRjM4bFI1VzdiYTFNCkFiMENxWGVpRkdnVDdmN2RMWTFl
            SDN0M2VtMVhuTUJibmhOUDdVRUVxQTgKLS0tIG9JNGF5REJONGd3cnEwMGd0QjU1
            bVZWZGsvbC9ldVFEOGZ4NER6eHNGOFUKsSQKZvZPI18BZMMgJjVq9n8bbyBexXKi
            SJB8dNE6FqKNi6yNjY92pTJZxq4oMNByq/J/PG4q6TrpiZi6jmLPmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T09:12:21Z"
    mac: ENC[AES256_GCM,data:5+8NB9L95JuLxNkqnzP1Q4KjaHNxMxYoRCFP38flOQLFhvnegn/KnLc5qKgijV0LRTk2X7ATLlKnWfcKsJTBUOj/VfM0PXqGt606c/bEZlcL0F2TBevckMn0Oy4NDvdwz6tpfrxenD5Qeq0No20RUWWrLbJcTRhvUCwLmf0dTNY=,iv:i6qj7VneVKCskxYKxH/1zpD1AwoQ2tA7H4f455sVgoM=,tag:FI79WmI29cOUcJ/yzjwehg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
