apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: personal-agent

resources:
  - namespace.yaml
  - 02-pvc.yaml
  - 03-deployment.yaml
  - 04-cronjob-monitor.yaml
  - 05-cronjob-news.yaml

generators:
  - ksops-generator.yaml

generatorOptions:
  disableNameSuffixHash: true
