# postgres-secrets.yaml (antes da encriptação SOPS)
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: personal-agent
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MejzE0t393ow35EWocHNOqpYvp2rj54ekyye3xKf51I=,iv:aixr+do9VDOnidN/eZhFnR8sbWXaGoytS4F/4e6SJos=,tag:mhlExDb64Ba2C1Bu1fnRwg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:5VSkcSA+Rbc=,iv:4/nmlyPssn0NpH+ZwZZZALdZHKSMUB8ctOw4nfat+Eo=,tag:8n2GPGzQWLhu+tb8K6TKlw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:CZxQ+pA=,iv:VzKiRc73xDYVqkQ6wEnYHvC8OCHKik4yHsWKTshSmQk=,tag:LkAL9BLB5+5XqkEvRUE5YA==,type:str]
    PIA_DB_USER: ENC[AES256_GCM,data:/kdc,iv:RXg9t3gQuC4GWrtwLBG6grKImaAgbA+cdHlF2Gmh7fg=,tag:2BveFm4p0k/7+qtGmxeiWA==,type:str]
    PIA_DB_PASSWORD: ENC[AES256_GCM,data:Vn3bF1wX8o7UlhYrJ9fJg0+pD/CjXKKl5t8qrgpt1q8=,iv:Caa/hPzEjPJu867B99I1Hg54uUloWYgGFIZgvfZDy4c=,tag:0+fV7T9ZKGfZ+zl6nMeOOg==,type:str]
    #ENC[AES256_GCM,data:0JjGOp7j6XuFMYzj6Gc0DnNWAzYD8Tv6p2vYdnE=,iv:OJ9IjcQUZwoaobQbrxoJS4zqbWQUiS3DGPlk3N24QIo=,tag:qak7M5lpD6W4W/zCqCZBBQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:T+/Mh0ncEhJzH++afxVLbHlSFJZz+a6I+ZXKa/F/RIXhbPJetQ2fuJK61Li3eB3LWwcD3bvWwcWy/oMLjnwkGV+WRqjNKztjfF1ugyDegA==,iv:Ft6tvD/njCDrRYiWUOPf+fnUzcFP1o2DIePLNHUjG/A=,tag:relMPRvE5g5U73tlj3L4NQ==,type:str]
sops:
    age:
        - recipient: age1x6ka0u4tudyx4dsw2lc9apaejk5qvcmzx59j0ktkavfhjkepa54se0fpl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ1lzZTBHem9JNXFpRnJm
            TC92SnN1UlBhSGVJZFRWNWRUUXN2dktDckRVCk5vMlh4VnZLay90RDdjOHVydElM
            a1BaMk5CQzNoZXA2VmlUS2gwbk4wYm8KLS0tIFFRWnNwWXo1RW1HVGI0RzFpSHZy
            Rm5nZDM3emhvaDdTNVE3ck4rVEhLa3MKYZ0r4g2nCtjoIKpwn+wz66wml0gIZR18
            OXAg8K4rg27+8pINY67MtOgZmey1KxV/DL0DzqDLDudsnVCHjdQmBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T14:33:23Z"
    mac: ENC[AES256_GCM,data:L867PQp5Skve9hIRh5xnGBu8+beucl5Ll/eotZNR142jMiPdbCyOvlYDqKDCXNo0EHbfSwbs1+NbEz8j1eU8SJi0t9fB+M6NGpJxEYBGA/HW7isfKrDLl8XgUlxsMFwPHdXtUyQU+ktc6+L/Bog3xJ7oAIeOHDMCENcJWDEYSEQ=,iv:i7K+NIIWdQGjd4/o4Bu4pG54m+tSC3cuguu9K6ExvUA=,tag:h+bEFafaRLy/ZJZKZNnp8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
