---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-local
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain  #Retain para nunca perder dados acidentalmente
parameters:
  nodePath: /var/lib/postgres-data
