# 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personal-agent

resources:
- 01-postgres-config.yaml
- 02-postgres-pvc.yaml
- 03-postgres-statefulset.yaml
- 04-postgres-service.yaml
- 05-postgres-networkpolicy.yaml
- postgres-secrets.enc.yaml

generators: []
